### ISSUE TITLE
Date filter only allows going one year back

### ISSUE THREAD

**Issue by ronreiter** [ronreiter/anyway#15]

**Comment by BrkCoder** [comment]
I'm working on this one.
Ron,Do you want to assign to me?

**Comment by BrkCoder** [comment]
from what I saw,the minimum date is minDate: '01/01/2013' . Because of that ,the date filter can't going more than one year back. 
What will be the min date ?
I think it should be 01/01/2005 ,because it is the last date where we have records about car accidents, according to israel_archive_transport: http://www.cbs.gov.il/reader/archive/archive_transport_new.html.
I would be happy to hear you opinion about this issue.

**Comment by ronreiter** [comment]
Sounds good. Go for it
