### ISSUE TITLE
Should use environment variable for DB connection string

### ISSUE THREAD

**Issue by sagism** [ronreiter/anyway#16]

**Comment by sagism** [comment]
This is true for all settings as we should be able to modify them between prod and dev, and they shouldn't be in the clear on github. This is a starting point.

**Comment by ronreiter** [comment]
go for it, but please add a default and a way for us to work locally on the remote data.

**Comment by sagism** [comment]
Working locally on remote data should not be a problem but default will be a problem as default value would have to be in the code and that exposes us to hacking. Same goes for facebook credentials etc.
Thoughts?

**Comment by ronreiter** [comment]
OK, makes sense, especially because it's open source. We'll need to clean
the history as well because it's already committed.

On Wed, Oct 16, 2013 at 7:35 AM, sagism notifications@github.com wrote:

> Working locally on remote data should not be a problem but default will be
> a problem as default value would have to be in the code and that exposes us
> to hacking. Same goes for facebook credentials etc.
> Thoughts?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ronreiter/anyway/issues/16#issuecomment-26392345
> .

## 

Ron Reiter
[image: Facebook] http://www.facebook.com/ron.reiter [image:
Twitter]http://twitter.com/#!/ronreiter [image:
LinkedIn]http://www.linkedin.com/profile/view?id=4436607&locale=en_US&trk=tab_pro
Contact me: [image: Skype] ron.reiter

**Comment by robi-y** [comment]
See [here](http://ejohn.org/blog/keeping-passwords-in-source-control/) for an example how to encrypt a configuration file.
